version: '3.7'
services:
  app:
    build:
      context: ..
      dockerfile: api-products/Dockerfile
    image: api-products
    restart: unless-stopped
    container_name: api-products
    ports:
      - 3333:3333
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-products.entrypoints=web"
      - "traefik.http.routers.api-products.rule=Host(`jhon-test-api-products.jhonerick.me`)"
      - "traefik.http.routers.api-products.service=api-products"
      - "traefik.http.services.api-products.loadbalancer.server.port=3333"
    networks:
      - traefikProxyNet
networks:
  traefikProxyNet:
    external: true
